/******/ (function(modules) { // webpackBootstrap
/******/ 	// The module cache
/******/ 	var installedModules = {};

/******/ 	// The require function
/******/ 	function __webpack_require__(moduleId) {

/******/ 		// Check if module is in cache
/******/ 		if(installedModules[moduleId])
/******/ 			return installedModules[moduleId].exports;

/******/ 		// Create a new module (and put it into the cache)
/******/ 		var module = installedModules[moduleId] = {
/******/ 			exports: {},
/******/ 			id: moduleId,
/******/ 			loaded: false
/******/ 		};

/******/ 		// Execute the module function
/******/ 		modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);

/******/ 		// Flag the module as loaded
/******/ 		module.loaded = true;

/******/ 		// Return the exports of the module
/******/ 		return module.exports;
/******/ 	}


/******/ 	// expose the modules object (__webpack_modules__)
/******/ 	__webpack_require__.m = modules;

/******/ 	// expose the module cache
/******/ 	__webpack_require__.c = installedModules;

/******/ 	// __webpack_public_path__
/******/ 	__webpack_require__.p = "";

/******/ 	// Load entry module and return exports
/******/ 	return __webpack_require__(0);
/******/ })
/************************************************************************/
/******/ ([
/* 0 */
/***/ function(module, exports, __webpack_require__) {

	var __weex_template__ = __webpack_require__(1)
	var __weex_script__ = __webpack_require__(2)

	__weex_define__('@weex-component/438737d70e3f95e03e7ac16ce0c95ad5', [], function(__weex_require__, __weex_exports__, __weex_module__) {

	    __weex_script__(__weex_module__, __weex_exports__, __weex_require__)
	    if (__weex_exports__.__esModule && __weex_exports__.default) {
	      __weex_module__.exports = __weex_exports__.default
	    }

	    __weex_module__.exports.template = __weex_template__

	})

	__weex_bootstrap__('@weex-component/438737d70e3f95e03e7ac16ce0c95ad5',undefined,undefined)

/***/ },
/* 1 */
/***/ function(module, exports) {

	module.exports = {
	  "type": "container",
	  "style": {
	    "flexDirection": "column"
	  },
	  "attr": {
	    "value": "//row则为横向排列"
	  },
	  "children": [
	    {
	      "type": "text",
	      "style": {
	        "fontSize": function () {return this.size}
	      },
	      "attr": {
	        "value": function () {return this.title}
	      }
	    },
	    {
	      "type": "text",
	      "style": {
	        "fontSize": function () {return this.Title.size}
	      },
	      "attr": {
	        "value": function () {return this.Title.value}
	      }
	    },
	    {
	      "type": "text",
	      "attr": {
	        "value": function () {return this.firstName+' '+this.lastName}
	      }
	    },
	    {
	      "type": "text",
	      "attr": {
	        "value": function () {return this.fullName}
	      }
	    },
	    {
	      "type": "text",
	      "events": {
	        "click": "changeName"
	      },
	      "style": {
	        "marginLeft": 10
	      },
	      "attr": {
	        "value": "CHANGE NAME"
	      }
	    },
	    {
	      "type": "text",
	      "events": {
	        "click": "toggle"
	      },
	      "attr": {
	        "value": "Toggle"
	      }
	    },
	    {
	      "type": "image",
	      "attr": {
	        "src": "http://h.hiphotos.baidu.com/image/pic/item/5243fbf2b21193138ff8eeb167380cd791238d73.jpg"
	      },
	      "shown": function () {return this.shown}
	    },
	    {
	      "type": "image",
	      "attr": {
	        "src": "https://gw.alicdn.com/tps/TB11a2lKFXXXXbVXpXXXXXXXXXX-32-32.png"
	      }
	    }
	  ]
	}

/***/ },
/* 2 */
/***/ function(module, exports) {

	module.exports = function(module, exports, __weex_require__){'use strict';

	module.exports = {
	  data: function () {return {
	    size: 48,
	    title: 'Alibaba Weex Team',
	    Title: {
	      size: 30,
	      value: 'XDS JSK'
	    },
	    firstName: 'John',
	    lastName: 'Smith',
	    shown: true
	  }},
	  computed: {
	    fullName: {
	      get: function get() {
	        return this.firstName + ' ' + this.lastName;
	      },

	      set: function set(v) {
	        var s = v.split(' ');
	        this.firstName = s[0];
	        this.lastName = s[1];
	      }
	    }
	  },
	  methods: {
	    changeName: function changeName() {
	      this.fullName = 'Terry King';
	    },
	    toggle: function toggle() {
	      this.shown = !this.shown;
	    }
	  }
	};}
	/* generated by weex-loader */


/***/ }
/******/ ]);